export interface CuentasDto {
    IDCuenta: number
    IDEstablecimiento: number
    DireccionEstablecimiento: DireccionEstablecimientoDto
    IDPersona: number
    IDTipoIdentificacion: number
    NumeroIdentificacion: string
    DigitoChequeo: number
    TipoyNumeroIdentificacion: string
    NombreEstablecimiento: string
    TipoNegocio: string
    IDPersonaVendedor: number
    IDPrograma: number
    Programa: string
    IDPais: number
    Pais: string
    IDGrupoPersona: number
    GrupoPersona: string
    FechaBloqueo: string
    IDEstado: number
    Estado: string
    IDCausalEstado: number
    CausalEstado: string
    FechaEstado: string
    ConsolidarCuentaParaRedencion: boolean
    FechaAfiliacion: string
    Bloqueada: boolean
    IDMotivoBloqueo: number
    MotivoBloqueo: string
    FechaDesafiliacion: string
    Observaciones: string
    IDPersonaRegistro: number
    FechaRegistro: string
    IDPersonaActualizacion: number
    PersonaCuenta: string
    Empresa: string
    ClaseAfiliacion: string
    IDCluster: number
    Cluster: string
    IDPunto: number
    TipoPunto: string
    FechaActualizacion: string
    FechaUltimaActualizacionDatos: string
    SaldoPuntos: number
    PuntosEmitidos: number
    PuntosReservados: number
    PuntosRedimidos: number
    PuntosVencidos: number
    PuntosVencen1Mes: number
    PuntosVencen2Mes: number
    PuntosVencen3Mes: number
    lstPuntosVencimiento: LstPuntosVencimientoDto[]
    Error: Error
    TotalPuntosPorFacturas: number
    TotalPuntosPorMisiones: number
    IDReconocimiento: number
    TituloReconocimiento: string
    ImagenReconocimiento: string
    Reconocimiento: string
    PorcentajeAumento: number
    Email: string
    TelefonoCelular: string
    CodigoArea: string
    UUID: string
    NombresPersonaCuenta: string
    ApellidosPersonaCuenta: string
    IDPersonaEstablecimiento: number
    IDOcupacion: number
    Telefono1_establecimiento: string
    TipoTelefono1_establecimiento: string
    Telefono2_establecimiento: string
    TipoTelefono2_establecimiento: string
    Telefono3_establecimiento: string
    TipoTelefono3_establecimiento: string
    Email_establecimiento: string
    PuntosPorTransferencia: number
    VisualizacionMultiPunto: boolean
    CodigoAgenciaPpal: string
    CodigoExterno: string
    MostrarWelcomeKit: boolean
    IDGenero: number
    Genero: string
    FechaNacimientoConstitucion: Date
    Edad: number
    ValidacionEmail: boolean
    ValidacionTelefono: boolean
    ValidacionDireccion: boolean
  }

  export interface DireccionEstablecimientoDto {
    IDDireccion: number
    IDPersona: number
    IDTipoDireccion: number
    direccion: string
    ZIPCode: string
    IDCiudad: number
    nombreCiudadCorto: string
    nombreCiudadLargo: string
    NombreDepartamento: string
    Barrio: string
    IDTipoTelefono1: number
    Telefono1: string
    ExtTelefono1: string
    IDTipoTelefono2: number
    Telefono2: string
    ExtTelefono2: string
    IDTipoTelefono3: number
    Telefono3: string
    ExtTelefono3: string
    IDFuente: number
    principal: boolean
    Valida: boolean
    Vigente: boolean
    IDPersonaRegistro: number
    FechaRegistro: string
    IDPersonaActualizacion: number
    FechaActualizacion: string
    Observaciones: string
    X: number
    Y: number
    IDComuna: number
    IDBarrio: number
    IDCiudadGeo: number
    DeshabilitarDirecciones: boolean
  }

  export interface LstPuntosVencimientoDto {
    PuntosVencen: number
    FechaCorte: string
  }
